file = open('file.txt','r')
lines = file.readlines()
num_lines = len(lines)
file.seek(0)
text = file.read()
words = text.split()
num_words = len(words)
num_symbols = len(text)
file.close()
print(f"Кількість рядків: {num_lines}")
print(f"Кількість слів: {num_words}")
print(f"Кількість символів: {num_symbols}")
